-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS p09."PRODUCTO"
(
    codigo_barras bigint NOT NULL,
    precio_venta numeric NOT NULL,
    precio_compra numeric NOT NULL,
    fotografia text NOT NULL,
    stock smallint NOT NULL,
    id_categoria_fk integer NOT NULL,
    id_sucursal_pk character varying NOT NULL,
    PRIMARY KEY (codigo_barras)
);

CREATE TABLE IF NOT EXISTS p09."CATEGORIA"
(
    id_categoria integer NOT NULL,
    marca character varying(50) NOT NULL,
    descripcion text NOT NULL,
    PRIMARY KEY (id_categoria)
);

CREATE TABLE IF NOT EXISTS p09."PROVEEDOR"
(
    rfc_proveedor character varying(13) NOT NULL,
    nombre_proveedor character varying(60) NOT NULL,
    ap_materno_proveedor character varying(60),
    ap_paterno_proveedor character varying(60) NOT NULL,
    telefono_fk bigint NOT NULL,
    PRIMARY KEY (rfc_proveedor)
);

CREATE TABLE IF NOT EXISTS p09."CLIENTE"
(
    rfc_cliente character varying(13) NOT NULL,
    nombre_cliente character varying(60) NOT NULL,
    ap_materno character varying(60),
    ap_paterno character varying(60) NOT NULL,
    calle character varying(70) NOT NULL,
    numero smallint NOT NULL,
    estado character varying(60) NOT NULL,
    colonia character varying(60) NOT NULL,
    cp smallint NOT NULL,
    id_venta_fk character varying(10) NOT NULL,
    PRIMARY KEY (rfc_cliente)
);

CREATE TABLE IF NOT EXISTS p09."VENTA"
(
    id_venta character varying(10) NOT NULL,
    fecha_venta date NOT NULL,
    monto_total numeric NOT NULL,
    PRIMARY KEY (id_venta)
);

CREATE TABLE IF NOT EXISTS p09."SUCURSAL"
(
    id_sucursal character varying(10) NOT NULL,
    razon_social_sucursal character varying(100) NOT NULL,
    calle character varying(70) NOT NULL,
    numero smallint NOT NULL,
    estado character varying(60) NOT NULL,
    colonia character varying(60) NOT NULL,
    cp smallint NOT NULL,
    PRIMARY KEY (id_sucursal),
    UNIQUE (razon_social_sucursal)
);

CREATE TABLE IF NOT EXISTS p09."TELEFONO"
(
    num_telefono bigint NOT NULL,
    rfc_proveedor_fk character varying(13) NOT NULL,
    PRIMARY KEY (num_telefono, rfc_proveedor_fk)
);

CREATE TABLE IF NOT EXISTS p09."SURTE"
(
    fecha_surte date NOT NULL,
    rfc_proveedor_fk character varying(13) NOT NULL,
    id_sucursal character varying(10) NOT NULL,
    PRIMARY KEY (rfc_proveedor_fk, id_sucursal)
);

CREATE TABLE IF NOT EXISTS p09."GUARDA"
(
    monto_producto numeric NOT NULL,
    cantidad_producto smallint NOT NULL,
    id_venta_fk character varying(10) NOT NULL,
    codigo_barras_fk bigint NOT NULL,
    PRIMARY KEY (id_venta_fk, codigo_barras_fk)
);

ALTER TABLE IF EXISTS p09."PRODUCTO"
    ADD FOREIGN KEY (id_categoria_fk)
    REFERENCES p09."CATEGORIA" (id_categoria) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS p09."PRODUCTO"
    ADD FOREIGN KEY (id_sucursal_pk)
    REFERENCES p09."SUCURSAL" (id_sucursal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS p09."PROVEEDOR"
    ADD FOREIGN KEY (telefono_fk)
    REFERENCES p09."TELEFONO" (num_telefono) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS p09."CLIENTE"
    ADD FOREIGN KEY (id_venta_fk)
    REFERENCES p09."VENTA" (id_venta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS p09."TELEFONO"
    ADD FOREIGN KEY (rfc_proveedor_fk)
    REFERENCES p09."PROVEEDOR" (rfc_proveedor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS p09."SURTE"
    ADD FOREIGN KEY (rfc_proveedor_fk)
    REFERENCES p09."PROVEEDOR" (rfc_proveedor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS p09."SURTE"
    ADD FOREIGN KEY (id_sucursal)
    REFERENCES p09."SUCURSAL" (id_sucursal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS p09."GUARDA"
    ADD FOREIGN KEY (id_venta_fk)
    REFERENCES p09."VENTA" (id_venta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS p09."GUARDA"
    ADD FOREIGN KEY (codigo_barras_fk)
    REFERENCES p09."PRODUCTO" (codigo_barras) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;